### ISSUE TITLE
Same issue as #98 with using conditionally enabled variable

### ISSUE THREAD

**Issue by HansOlsson** [modelica/Modelica_DeviceDrivers#101]
Using conditional variable procPrio is also an issue in
Modelica_DeviceDrivers.ClockedBlocks.OperatingSystem.SynchronizeRealtime
(same solution should apply here).

**Comment by tbeu** [comment]
Thanks for testing and pointing to it. I forgot to merge.

**Comment by tbeu** [comment]
Hm, should I have this `Boolean initialized(start=false);` both in the SynchronizeRealtime and its (new) sub-block ProcessPriority?

**Comment by HansOlsson** [comment]
As I understand it the reason for 'initialized(start=false)' was to ensure that the process-priority was set before the other call in the algorithm. 

Either that is isn't important (it will have the right priority sometime during initialization; might be close enough - in some systems it might be preferable to enable real-time priority after initialization allowing the initialization to take additional time), or it is important (the other call may fail if incorrect priority) - in which case it will take a bit of extra work to handle it. (Using connectors etc.)

**Comment by tbeu** [comment]
Would it also work with initial algorithm? This can also be evaluated more than once (as it currently is with `initialized(start=false)`.
