### ISSUE TITLE
CI @ drone.io

### ISSUE THREAD

**Issue by tbeu** [modelica/Modelica_DeviceDrivers#102]
@dietmarw @bernhard-thiele @bradrydzewski I added CI at [drone.io](https://drone.io/github.com/modelica/Modelica_DeviceDrivers) for fun in order to run some of the tests automatically.

I got even test_MDDComedi successfully compiling and linking but on amd64 only. Somehow
```sh
sudo apt-get install -qq -y libcomedi-dev
```
works whereas
```sh
sudo apt-get install -qq -y libcomedi-dev:i386
```
always gives `E: Unable to correct problems, you have held broken packages.` no matter what I do.

**Comment by dietmarw** [comment]
@tbeu Does this also happen when you start on a fresh build for i386 without building 64bit before?

**Comment by tbeu** [comment]
Yes, it happens already at a fresh build.

**Comment by tbeu** [comment]
This is now delegated to drone/drone#1230

**Comment by tbeu** [comment]
I asked via the drone.io contact formular some 10 days ago but did not get any reply.

**Comment by bernhard-thiele** [comment]
Cool. Quite an amazing service that you have set up :-)
