### ISSUE TITLE
Move Incubate to own branch

### ISSUE THREAD

**Issue by tbeu** [modelica/Modelica_DeviceDrivers#111]
@bernhard-thiele OK for you?

**Comment by bernhard-thiele** [comment]
Would like to keep it in master for the moment. I think some of it is used by some DLR applications. Also, if pakcage or class names in the library are changed tools can automatically adapt all the references to this names in `Incubate`.

We can keep that ticket open and decide upon it before the next milestone, but I don't want to rush into a change here.

**Comment by tbeu** [comment]
OK, keep it for now.
