### ISSUE TITLE
USB/Bluetooth support wanted?

### ISSUE THREAD

**Issue by tbeu** [modelica/Modelica_DeviceDrivers#116]
@bernhard-thiele Collecting more ideas: https://github.com/signal11/hidapi is a platform independent implementation for USB and Bluetooth communication by the HID API. Do you think it might be useful to have it supported with M_DD?

**Comment by bernhard-thiele** [comment]
Could be nice to have. Of course it would add additional dependencies and maintenance efforts, hence it would be good to know if there are any interested users or use cases that you have in mind. Alternatively, one could think on using the OS APIs directly, so that no additional third party dependency is added.

**Comment by vwaurich** [comment]
I would be very interested. I have to put some effort in this topic soon and it would be nice to know which api you prefer.

**Comment by tbeu** [comment]
Thanks for you interest. I'd go for the HID API, because
* it is platform independent already
* we do not have to re-invent the effort
* we have successfully proven to manage third-path libraries (like glib-2.0 and lcm for #115).

**Comment by vwaurich** [comment]
I am not an expert on that, but I think hid api offers support for hid bluetooth profile only. If I want to send and reveice data like in a serial port, I need spp profile. hdi-api can be implemented but the use cases are limited to hdi, am I right? https://learn.sparkfun.com/tutorials/bluetooth-basics

**Comment by tbeu** [comment]
Good point. If SSP is what you need then HID API is not the API of choice.

**Comment by vwaurich** [comment]
I tried to send data via bluetooth to a modelica simulation in dymola under windows.
It did work without any modification at the serial port code because you can handle bluetooth connections like ordinary COM ports under Windows. But it still shows some arbitrary behaviour. It works only every third time. Thats weird. I will investigate this.

**Comment by tbeu** [comment]
With your patch applied I guess?

**Comment by vwaurich** [comment]
@tbeu Yes, but it should have no effect on the weird behaviour. When its not working properly it doesnt call ReadFile at all. What I would like to state is, that I dont think we need an additional implementation that tackles bluetooth. Sending and receiving should work with the current serial code. Or are there any other applications of interest except SPP?

**Comment by vwaurich** [comment]
If I have a working setup, I can also try it on linux.

**Comment by tbeu** [comment]
If Bluetooth via SSP is working for you, we can be glad to have less work. HID might not be of that interest. I only learned now.
What about USB?

**Comment by vwaurich** [comment]
Oh...I did not mentioned yet,, that I always use the serial port via usb? So this should be done with my patch.

**Comment by tbeu** [comment]
Can you give me some clue where is wire and where wireless communication. I cannot imagine right now.

**Comment by vwaurich** [comment]
@tbeu Sorry, I dont get the question.

**Comment by tbeu** [comment]
Well, bluetooth is wireless communication. Now that you use (wired?) serial I/O I wonder where there still is wireless I/O? Maybe a stupid question. Thus, would be interesting to read about the application  :smirk:.

**Comment by vwaurich** [comment]
The application is reading angular sensors with an arduino and transfering them via a serial usb connection. The same task can be accomplished using a hc-05 bluetooth module to use the arduino without usb connection. Some students developed a mobile handheld control device (like a joystick) and therefore it needs to be wireless.

**Comment by tbeu** [comment]
I guess it is ok to close since Bluethooth is working via serial port i/o.
