### ISSUE TITLE
SerialPort receiver thread overwrites results

### ISSUE THREAD

**Issue by sjoelund** [modelica/Modelica_DeviceDrivers#117]
The implementation of the serial port receiver currently has the same behavior as UDP when receiving a `package`. The problem is that every single byte is polled and received individually especially when sent at a lower baud.

It would be nicer if one would send in the number of bytes to read (via a packager) to the read function, and just let the buffer be a buffer that was filled up when receiving messages and cleaned when reading (but only removing the requested number of bytes). Or at the very least if multiple bytes were received over a serial port, that the packages were appended.

**Comment by bernhard-thiele** [comment]
I will work on this (related #119, #127)

**Comment by bernhard-thiele** [comment]
I will close this issue since #128 should have solved the issue for Linux and the Windows related discussion has started at #127.
