### ISSUE TITLE
MQTT client

### ISSUE THREAD

**Issue by tbeu** [modelica/Modelica_DeviceDrivers#130]
See [Wikipedia](https://en.wikipedia.org/wiki/MQTT) and [mqtt.org](http://mqtt.org/) for an description of  the Message Queuing Telemetry Transport protocol and its usage for the Internet of Things.

Based on the experience with LCM and the TCP/IP and by wrapping the platform-generic [Eclipse Paho MQTT C client](https://github.com/eclipse/paho.mqtt.c) I am going to implement an MQTT client for both asynchronous and synchronous communication. Development branch is `mqtt`.

@vwaurich FYI

**Comment by tbeu** [comment]
@vwaurich @bernhard-thiele I already started a client implementation. I guess it will be finsihed after the article submission and before the next release / Modelica conference.

Implementation is straith-forward actually, similar to LCM. Pthread dependency is only needed on Linus, but not in Win.

**Comment by PMehrfeld** [comment]
I just noticed this interesting approach for implementing a MQTT solution for Modelica. Is this still planned for v1.6.0. And if so, does already exist an official release date?

Thanks a lot in advance.

**Comment by bernhard-thiele** [comment]
There exists first prototypical work by @tbeu, but I don't know whether that has matured or whether it is on hold.

There is no planned release date for v1.6.0, yet. It will be released as soon as there are some suitably mature new features in the master branch. This is currently not the case (but I agree that it would be nice to have it in a not too far away future).

**Comment by tbeu** [comment]
@PMehrfeld I restarted work on the MQTT client solution for Modelica. Do you already know if you require SSL support? I'd skip it otherwise in the first implementation.

**Comment by PMehrfeld** [comment]
@tbeu : Glad to here that you are proceeding the work on the MQTT solution. No, we do not need SSL support.

**Comment by tstorek** [comment]
@tbeu thank you in advance. If possible ssl support would be an interesting feature for some use cases.

**Comment by tbeu** [comment]
@tstorek Good news, I've got atll the environment set up and managed to connect with [test.mosquitto.org](http://test.mosquitto.org) using ports 1883 (MQTT, unencrypted), 8883 (MQTT, encrypted) and 8884 (MQTT, encrypted, client certificate required) (on Windows, based on the simple test in https://github.com/eclipse/paho.mqtt.c/issues/240). Support of websockets is currently in development for [paho.mqtt.c](https://github.com/eclipse/paho.mqtt.c), but not yet released. Let me know, if you required it already now, but I'd rather prefer to stay at [v1.2.1](https://github.com/eclipse/paho.mqtt.c/releases/tag/v1.2.1), which is the latest release.

**Comment by tbeu** [comment]
Status update: I successfully tested paho.mqtt.c with websocket support, which will be released in a few weeks as v1.3.0.
