### ISSUE TITLE
Improve memory allocation handling in socket CAN receiver (Linux)

### ISSUE THREAD

**Issue by tbeu** [modelica/Modelica_DeviceDrivers#141]
ModelicaAllocateString is called in MDD_socketCANRead, which terminates the complete simulation in case of a memory allocation error. The recommended workaround is to call ModelicaAllocateStringWithErrorReturn instead with proper error handling.

See #120 for the general issue.

**Comment by sjoelund** [comment]
Note: The simulation is not terminated if MdoelicaAllocateString is called. It is the same as a failed Modelica assert() or calling ModelicaError. The simulation should be able to recover from this.

**Comment by tbeu** [comment]
I beleive in case of SimulationX the simulation stops at ModelicaError. And the [default implementation](https://github.com/modelica/Modelica_DeviceDrivers/blob/master/Modelica_DeviceDrivers/Resources/test/Util/ModelicaUtilities.c#L35-L39) of ModelicaAllocateString is to call ModelicaError in case of memory allocation error. The new ModelicaWarning is thought to be similar as Modelica assert().

**Comment by sjoelund** [comment]
You are wrong. ModelicaWarning is the same as the warning assertion level. And ModelicaError is the same as the (default) error assertion level. At least Dymola and OpenModelica will try with a shorter step size when an assertion triggers (to see if the assertion can be avoided by reducing numerical errors).

**Comment by tbeu** [comment]
Thanks for the clarification. Do you have a nice little example, that I could use to debug and check for ModelicaError? Unfortunately there is none in https://github.com/modelica-compliance/compliance and the [one example](https://github.com/modelica-compliance/compliance/issues/10) that I found is not suitable.

**Comment by sjoelund** [comment]
I guess there should be examples in there using assert. It should be possible to take any of them and replace assert with an external function calling ModelicaError instead.

However, ModelicaCompliance models should work with pretty much any numerical solver so I wonder if retries are actually good for it. I suppose we could have an external function that fails only the first time you call it and put it as part of an algebraic loop?

**Comment by tbeu** [comment]
From SimulationX I know that assert with default error level behaves as expected. But I am not sure for ModelicaError right now.

> I suppose we could have an external function that fails only the first time you call it and put it as part of an algebraic loop?

Yes, exactely.

**Comment by tbeu** [comment]
Documentation of Modelica.Utilities.Streams.error = ModelicaError says: "Print ... error message and cancel all actions."

**Comment by sjoelund** [comment]
The actual Modelica Spec says:
> Output the error message string (no format control). This function never returns to the calling function, but handles the error similarly to an assert in the Modelica code.

**Comment by tbeu** [comment]
Could be improved to: "... but handles the error similarly to an assert with (default) error level in the Modelica code."

**Comment by tbeu** [comment]
Ah, upcoming MLS 3.4 has already:

> The error functions never returns to the calling function, but handles the error similarly to an assert with assertionLevel=AssertionLevel.Error in the Modelica code.

**Comment by tbeu** [comment]
OK, it is a bug in SimulationX: The test model [https://gist.github.com/tbeu/c88491301aded27fe00600cc56b2643d](ModelicaErrorOnce) fails.

**Comment by tbeu** [comment]
Cross reference: https://github.com/modelica-compliance/compliance/pull/19

**Comment by bernhard-thiele** [comment]
I suppose this ticket can be closed? Reopen, if necessary.

**Comment by tbeu** [comment]
OK for me. There also is no memory leak if ModelicaAllocateString fails.

Thanks for discussing and clarifying it.
