### ISSUE TITLE
Serial port / UDP sender should not destroy the external object in case of error (Linux)

### ISSUE THREAD

**Issue by tbeu** [modelica/Modelica_DeviceDrivers#145]
* MDD_serialPortSend destroys the object by calling MDD_serialPortDestructor in case of error.
* MDD_udpSend destroys the object by calling MDD_udpDestructor in case of a sendto error.

This is not required and I also believe it is a programming error to do so.

See #120 for the general issue.

**Comment by bernhard-thiele** [comment]
Yes, it's strange that they are there. Don't remember whether there was some reason behind it, but in theory they shouldn't be needed. I will remove them.
