### ISSUE TITLE
Unused mutex for serial port / UDP sender (Linux)

### ISSUE THREAD

**Issue by tbeu** [modelica/Modelica_DeviceDrivers#146]
MDD_serialPortConstructor / MDD_udpConstructor always initializes the messageMutex where it actually is only needed for the receiver.

See #120 for the general issue.

**Comment by tbeu** [comment]
Sorry, to open again, but ticket is on both MDD_udpConstructor and MDD_serialPortConstructor.

**Comment by bernhard-thiele** [comment]
Not that this changes really matter, it's small code beautifications at best...

**Comment by tbeu** [comment]
Do not understand ... You moved the `pthread_mutex_init` to the `if (receiver)` block. This is more than cosmetics, but what this ticket actually is about.

**Comment by bernhard-thiele** [comment]
It is now only initialized for receiving sockets. Before that it was always initialized, which didn't do any harm either.

**Comment by tbeu** [comment]
So I'd call it a semantical change rather than a cosmetical one. This issue was about unsued mutex.

**Comment by bernhard-thiele** [comment]
I've just seen #144 and the simplest way to cater for it seems to always initialize the mutex and always destroy it. That minimizes conditionals and keeps the code simple.

**Comment by tbeu** [comment]
All Linux issues are connected to #120 and also linked from there.
