### ISSUE TITLE
Microcontroller icon text and font size

### ISSUE THREAD

**Issue by tbeu** [modelica/Modelica_DeviceDrivers#186]
The font (size) in icon Modelica_DeviceDrivers.EmbeddedTargets.AVR.Blocks.Microcontroller is intrepreted differently in three tested tools:

Dymola 2017 FD01
![dymola_blink](https://cloud.githubusercontent.com/assets/5444067/21487011/7290cc58-cbbf-11e6-84a5-1c88cc72b7f5.png)

MWorks Sysplorer 2016
![mworks sysplorer_2016_blink](https://cloud.githubusercontent.com/assets/5444067/21487015/87acf0c6-cbbf-11e6-98c6-19b5b2ed6ff2.png)

SimulationX 3.8
![simx_blink](https://cloud.githubusercontent.com/assets/5444067/21487018/92f0de8e-cbbf-11e6-8b7e-802fcd682c20.png)

Not sure what the desired behaviour is and if this is a MLS issue actually.

See #170 for the general issue on MCU support.

**Comment by tbeu** [comment]
@sjoelund Did you had a look on this?

**Comment by sjoelund** [comment]
Changing size to 0 would probably work fine (renders in almost the exact same size in OMEdit). Odd that each tool has a vastly different size for 30 pt though. SimulationX looks like it's 200~250 pt. The Real-time block is rendered decently in all tools and that uses size=0 for the font size.

**Comment by tbeu** [comment]
Yes, strange indeed.

**Comment by tbeu** [comment]
I believe the problem is the extend interpretation for font size > 0. It looks like its size can be neglected and is only considered for font size = 0.

**Comment by sjoelund** [comment]
Yes, but that doesn't answer why the font size is so different in the different tools...

**Comment by tbeu** [comment]
It is similar for Dymola and SimulationX. What is different is the vertical size of the line break.

![2017-01-19 10_00_43-unnamed - simulationx 3 8 professional edition](https://cloud.githubusercontent.com/assets/5444067/22100072/384b2008-de2e-11e6-80e1-d2fd30664185.png)

```mo
model A
  annotation(
    Icon(
      graphics={
        Text(
          extent={{-450,450},{450,-450}},
          lineColor={28,108,200},
          fontName="Arial",
          textStyle={TextStyle.Bold},
          textString="ABCD\nABCDEF",
          fontSize=30),
        Rectangle(
          extent={{-100,100},{100,-100}},
          lineColor={28,108,200})}));
end A;
```

**Comment by tbeu** [comment]
FYI: I'll file a SimulationX ticket for neglecting the font size in case of absolute font size.

**Comment by dietmarw** [comment]
OMEdit:
![image](https://cloud.githubusercontent.com/assets/9332/22146490/18ded642-df05-11e6-87b3-fde948d1e23a.png)

**Comment by tbeu** [comment]
MWorks:
![2017-01-20 11_48_35-mworks sysplorer 2016 demo - model2](https://cloud.githubusercontent.com/assets/5444067/22146851/73cb580e-df06-11e6-98c5-4d1c73352052.png)
