### ISSUE TITLE
What is package lmodern used for?

### ISSUE THREAD

**Issue by tbeu** [modelica/Modelica_DeviceDrivers#191]
Martin, for what reason did you add `\usepackage{lmodern}` by b5713516c7c6a4468068146bd46deb8c9b2732fa for #188? In consequence, the code listings for e.g., ` GameControllerExample` or `getFoo` really have unsuitable line breaks. I'd propose to remove `lmodern` again.

See #126.

**Comment by sjoelund** [comment]
It's used for the proper ℃ symbol. The regular ones look really bad.

**Comment by tbeu** [comment]
The difference is marginal, but the side-effects are significant
![2017-01-16 21_05_18-modelica2017_modelica_devicedrivers pdf - towards a standard-conform platform-](https://cloud.githubusercontent.com/assets/5444067/21997436/a78c1c34-dc2f-11e6-9c81-4b8d72efe8d1.png) ![2017-01-16 21_05_45-modelica2017_modelica_devicedrivers pdf - towards a standard-conform platform-](https://cloud.githubusercontent.com/assets/5444067/21997437/a909a932-dc2f-11e6-981a-73053b14c4af.png)
The `\degreecelsius` from `\usepackage[squaren,thinqspace]{SIunits}` ( what I usually use) looks pretty identical to default (non-lmodern) style.
![2017-01-16 21_11_54-modelica2017_modelica_devicedrivers pdf - towards a standard-conform platform-](https://cloud.githubusercontent.com/assets/5444067/21997601/7bacce50-dc30-11e6-80d0-bab345264654.png)

**Comment by tbeu** [comment]
And this is `$\SI{0}{\degreeCelsius}$` from `\usepackage{siunitx}` and `\usepackage{amsmath}`.
![2017-01-16 21_37_19-modelica2017_modelica_devicedrivers pdf - towards a standard-conform platform-](https://cloud.githubusercontent.com/assets/5444067/21998270/1d2b652c-dc34-11e6-9398-34e554b24b3f.png)

**Comment by sjoelund** [comment]
Feel free to change it any way you want due to the side-effects. The lmodern one does look nicer than the alternatives though.

**Comment by tbeu** [comment]
OK. With next PR.
