### ISSUE TITLE
\noindent

### ISSUE THREAD

**Issue by tbeu** [modelica/Modelica_DeviceDrivers#194]
@sjoelund You introduced `\noindent` after figures in the hope that the figure will always be placed exactely before the next paragraph. This is not the case. In result, there are now non-indented paragraphs next to indented paragraphs w/o any figure. See page 3 of the article from #126. Please review. Thanks.

**Comment by sjoelund** [comment]
Seems to be the annoying `[htb]` specififer. Earlier, the figure was inline with the paragraphs (`h`) and required noindent. Now it's a float on a different page (`t`), so noindent shouldn't be used...

**Comment by sjoelund** [comment]
See #196

**Comment by tbeu** [comment]
Thanks.
