### ISSUE TITLE
Delete superseded branches

### ISSUE THREAD

**Issue by bernhard-thiele** [modelica/Modelica_DeviceDrivers#217]
I think following branches are not needed any more and can be deleted:

- lcm (integrated into master)
- pthread-win32 (change in OM that solved the issue)

@tbeu Agree or do I miss something?

**Comment by tbeu** [comment]
Fine to delete lcm. However pthread-win32 was experimental for #114 which is still open.

**Comment by bernhard-thiele** [comment]
Ok, thanks I deleted lcm. I was thinking the pthread problem has been solved by a changes to OM and maybe #114 can be closed. I think we should check whether we can close #114. It was a long discussion, but at least to my understanding we have now a "workaround" implemented in OM.
