### ISSUE TITLE
Missing print arguments in MDDSharedMemory.h

### ISSUE THREAD

**Issue by d94pn** [modelica/Modelica_DeviceDrivers#235]
In MDDSharedMemory.hm line 248 and 261 misses the argument to %s, and should be:

ModelicaFormatMessage("Shared memory object '%s' seems to be already removed (possibly by remote process)\n"**, smb->shmname**);

ModelicaFormatMessage("Semaphore '%s' seems to be already removed (possibly by remote process)\n", **smb->semname**);

**Comment by bernhard-thiele** [comment]
Thanks for the report!
