### ISSUE TITLE
Support blocking UDP receive call

### ISSUE THREAD

**Issue by bernhard-thiele** [modelica/Modelica_DeviceDrivers#275]
Rationale: Support of a blocking UDP receive call allows synchronizing a simulation to an external application sending the UDP datagrams.

The proposal is to add an option `useRecvThread` to the UDPReceive block. So far a separate thread is created for receiving datagrams (corresponds to the proposed default value `useRecvThread=true`). By setting the option to `false` a user can prevent that a separate thread is created and simulation progress is blocked when calling out to UDP `recvfrom(..)`.

![grafik](https://user-images.githubusercontent.com/4244614/52127079-56060980-2631-11e9-82cd-9971c70a65c9.png)

**Comment by bernhard-thiele** [comment]
Yes, I'm not sure what the better word is. But thinking about it, I lean to "dedicated". I will change it.

**Comment by beutlich** [comment]
> I will change it.

Thanks.

And please also add a separate test for it.

**Comment by bernhard-thiele** [comment]
I've now  also successfully tested the code using OpenModelica running on Linux. The code seems okay and thus I squashed & merged it.
