### ISSUE TITLE
Deprecated icons in v1.7.0

### ISSUE THREAD

**Issue by UlfNordstrom** [modelica/Modelica_DeviceDrivers#282]
Two classes extends Modelica.Blocks.Interfaces.BlockIcon wich is marked as deprecated "This icon will be removed in future Modelica versions, use Modelica.Blocks.Icons.Block instead".
- Modelica_DeviceDrivers.EmbeddedTargets.AVR.Examples.SBHS.Board
- Modelica_DeviceDrivers.EmbeddedTargets.AVR.Examples.SBHS.Controller
![image](https://user-images.githubusercontent.com/26482906/54672477-6ea28400-4af8-11e9-94f1-96bad7ed04f4.png)

For SBHS.Board the path in the extends clause start with a "."

_extends .Modelica.Blocks.Interfaces.BlockIcon;_

**Comment by tbeu** [comment]
> For SBHS.Board the path in the extends clause start with a "."

Which is legal Modelica for referencing classes from top-level.
