### ISSUE TITLE
Linux support of SoftingCAN

### ISSUE THREAD

**Issue by tbeu** [modelica/Modelica_DeviceDrivers#41]
In Softing's download center I can see a "CAN-AC PCI V5.18 Driver for Linux Kernel 3.2 (Kubuntu 12.04 LTS)". Does this mean that SoftingCAN could be ported to Linux?

**Comment by tbeu** [comment]
This means won't fix then (or can't fix).

**Comment by bernhard-thiele** [comment]
I can't fix it (no hardware to test). But if somebody has the hardware and gets the drivers running under Linux it is probably very easy to port it.
