### ISSUE TITLE
Rebuild binaries in master

### ISSUE THREAD

**Issue by tbeu** [modelica/Modelica_DeviceDrivers#49]
Bernhard, can you please rebuild and update the binaries of the master branch. Thank you.

**Comment by bernhard-thiele** [comment]
I didn't rebuild the space mouse and CAN part, since I guess it was ITI_MDD.dll that the needed an update due to changes in the real-time synchronization code. Hope that closes the issue.

**Comment by tbeu** [comment]
Can you please use again VS2010. Otherwise it will not work on WinXP. Thank you.

**Comment by bernhard-thiele** [comment]
Any way to set options to VS2013 to make it work?

My notebook SSD is a bit short on disk space ...

**Comment by tbeu** [comment]
I see. I try to do it on my own though I have no Cmake experience at all. I'll push to my fork then,

**Comment by tbeu** [comment]
Do you consider to merge the VS2010 binaries?

**Comment by bernhard-thiele** [comment]
I've been away for a few days. Just merged it. Thanks for providing the VS2010 builds.

**Comment by tbeu** [comment]
Thanks. This makes it easier for me if your master and my forked master are in sync.
