### ISSUE TITLE
Support of big endian

### ISSUE THREAD

**Issue by tbeu** [modelica/Modelica_DeviceDrivers#66]
Customer uses UDPSend to send data (double, float, int32) to external tool. He noticed that only little endian is supported whereas external tool expects big endian.
It would be nice if byte order layout could be chosen in UDP (and similar) blocks. Or should it go to Packager or Add/Get blocks? I can do it but would like to know where it belongs best?
@bernhard-thiele Please advice quickly since customer askes for it.

**Comment by bernhard-thiele** [comment]
I think it fits better at the Add/Get blocks, though both solutions make sense of course.

If I remember correctly at least one popular tool for specifying CAN message databases allows to set the endianness for any signal within the message separately. Hence, it probably makes sense to support it at the Add/Get blocks.
