### ISSUE TITLE
UDPLib

### ISSUE THREAD

**Issue by tbeu** [modelica/Modelica_DeviceDrivers#82]
Do you know the [UDPLib](http://www.euclides.dia.uned.es/UDPLib/index.html)?

**Comment by bernhard-thiele** [comment]
No, never heard of it. Just downloaded it. Seems to be quite basic and rather unmaintained. Don't think that this is interesting for us, or do you think differently?

**Comment by tbeu** [comment]
The only thing what I consider useful this the absence of the package manager. Thus if you know that you need to send/receive n doubles this specialized implemenentation probably is easier.
