### ISSUE TITLE
Please test with SimVis

### ISSUE THREAD

**Issue by tbeu** [modelica/Modelica_DeviceDrivers#94]
@tbellmann: Can you please verify that recent M_DD v1.4.2 works on DLR together with SimVis? Otherwise there might be need to add some defines in same way as https://github.com/DLR-SR/Noise/issues/34#issuecomment-125771660 for the C code of the Noise lib.

@MartinOtter: For reference.

**Comment by tbeu** [comment]
Well, there probably is one
```c
#if !defined(WIN32_LEAN_AND_MEAN)
#define WIN32_LEAN_AND_MEAN
#endif
```
missing before
```c
#include <windows.h>
```
in MDDSoftingCAN.h. Can test it next week if it still compiles then.

**Comment by tbellmann** [comment]
A short test under windows combining the Version: 1.4.2, 2015-09-14 of the MDD with 1.4 Beta Visualization library worked fine. I tested all UDP and Shared Memory blocks, as well  as most of the input devices. Not testet: CAN and TCP.
